version: 2
before:
  hooks:
    - make web
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dock-pulse
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/justxxi/dock-pulse/internal/version.Version={{.Version}} -X github.com/justxxi/dock-pulse/internal/version.Commit={{.ShortCommit}} -X github.com/justxxi/dock-pulse/internal/version.BuildDate={{.Date}}
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
